{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ $fullName }}
spec:
  secretName: {{ $fullName }}-tls  # this is the secret where the certificate is actually stored
  dnsNames:
  {{- range .Values.ingress.hosts }}
    - {{ .host }}
  {{- end }}
  issuerRef:
    name: {{ .Values.ingress.letsencrypt.issuerName }}  # this is name of the certificate issuer to use
    kind: ClusterIssuer  # since you created cluster issuers earlier the kind here must be ClusterIssuer
  acme:
    config:
      - http01:
          ingress: {{ $fullName }}
        domains:
        {{- range .Values.ingress.hosts }}
          - {{ .host | quote }}
        {{- end }}
{{- end }}