version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Building based image.
          command: docker build -f Dockerfile -t $DOCKER_REGISTRY/$DOCKER_USER/homepage:v$CIRCLE_BUILD_NUM .
      - run:
          name: Building ARM based image.
          command: docker build -f Dockerfile.arm64v8 -t $DOCKER_REGISTRY/$DOCKER_USER/homepage:armv$CIRCLE_BUILD_NUM .

      - run:
          name: Docker registry login
          command: docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Docker registry push
          command: |
            docker push $DOCKER_REGISTRY/$DOCKER_USER/homepage:v$CIRCLE_BUILD_NUM
            docker push $DOCKER_REGISTRY/$DOCKER_USER/homepage:armv$CIRCLE_BUILD_NUM
