version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Enabling qemu
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Building arm based image.
          command: docker build -t $DOCKER_REGISTRY/$DOCKER_USER/homepage:arm .
      - run:
          name: Listing built images
          command: docker images
      - run:
          name: Docker registry login
          command: docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker registry push
          command: docker push $DOCKER_REGISTRY/$DOCKER_USER/homepage:arm
