version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA

      - kube-orb/install-kubectl

      - helm/install-helm-client:
          version: v3.0.2

      - run:
          name: Building based image.
          command: docker build -f Dockerfile -t $DOCKER_REGISTRY/$DOCKER_USER/homepage:v$CIRCLE_BUILD_NUM .
      - run:
          name: Building ARM based image.
          command: docker build -f Dockerfile.arm64v8 -t $DOCKER_REGISTRY/$DOCKER_USER/homepage:armv$CIRCLE_BUILD_NUM .

      - run:
          name: Docker registry login
          command: docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Docker registry push
          command: |
            docker push $DOCKER_REGISTRY/$DOCKER_USER/homepage:v$CIRCLE_BUILD_NUM
            docker push $DOCKER_REGISTRY/$DOCKER_USER/homepage:armv$CIRCLE_BUILD_NUM

      - run:
          name: Add Helm repo
          command: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

      - run:
          name: Install Helm chart
          command: helm upgrade homepage ./chart --set image.version=armv$CIRCLE_BUILD_NUM --install

orbs:
  kube-orb: circleci/kubernetes@0.11.0
  helm: circleci/helm@0.2.3
